tests: add secp256k1 Point validity and de/encoding test vectors
verklegarden/crysol pull request #32
Opened 2024-10-10 21:54 UTC by obatirou

This PR is part of https://github.com/verklegarden/crysol/issues/23.
It adds the tests vectors for point validity and de/encoding and allows to test:
* `mul`
* `add`
* `IsOnCurve`
* `pointFromEncoded`
* `pointFromCompressedEncoded`

The addition of those tests allowed to catch a bug: `isOnCurve` was missing a check on coordinate that needs to be inferior to `P`

2024-10-10 22:14 UTC, obatirou commented on test/onchain/secp256k1/Secp256k1Arithmetic.t.sol
> +    function testVectors_Point_isPoint_noble_curves() public {
Not sure how the naming for this one. Maybe this should be put in the (De)Serialization part. But at the same time it test if the point is on the Curve.

2024-10-11 21:03 UTC, pmerkleplant requested changes
This is very clean work, thank you so much! And another bug fixed too :100: 🙏

2024-10-14 19:51 UTC, obatirou commented on foundry.toml
> +fs_permissions = [{ access = "read", path = "./" }]
done with [558f004](https://github.com/verklegarden/crysol/pull/32/commits/558f00447c1de2b946391633ee874e4a000016b9)

2024-10-14 19:52 UTC, obatirou commented on test/onchain/secp256k1/Secp256k1Arithmetic.t.sol
> +            assertEq(wrapper.isOnCurve(point), expectedOnCurve);
done with [338da85](https://github.com/verklegarden/crysol/pull/32/commits/338da859b32e422100a1ffc375f1b4331d825f21)

2024-10-14 19:52 UTC, obatirou commented on test/onchain/secp256k1/Secp256k1Arithmetic.t.sol
> +    function testVectors_Point_isPoint_noble_curves() public {
Made the rename for easier grepping with [59a03ce](https://github.com/verklegarden/crysol/pull/32/commits/59a03cecbee2b375c8d2a730cb0bf3a96eb0685d)

2024-10-15 08:03 UTC, pmerkleplant approved these changes

2024-10-15 08:05 UTC, merged